### ISSUE TITLE
encapsia database backup fails when tmp and destination are on different devices

### ISSUE THREAD

**Issue by adiniscmed** [tcorbettclark/encapsia-cli#14]
encapsia database --host adi-test.encapsia.com backup /backups/daily/adi-test/Friday/adi-test.encapsia.com-201219.sql
Backing up database....Done
Traceback (most recent call last):
  File "/usr/local/bin/encapsia", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/encapsia_cli/database.py", line 28, in backup
    temp_filename.rename(filename)
  File "/usr/lib/python3.6/pathlib.py", line 1309, in rename
    self._accessor.rename(self, target)
  File "/usr/lib/python3.6/pathlib.py", line 393, in wrapped
    return strfunc(str(pathobjA), str(pathobjB), *args)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpncvu23yb' -> '/backups/daily/adi-test/Friday/adi-test.encapsia.com-201219.sql'

**Comment by adiniscmed** [comment]
Created Pull request https://github.com/tcorbettclark/encapsia-cli/pull/15 to propose solution

**Comment by tcorbettclark** [comment]
PR #15 merged. Closing bug.
