### ISSUE TITLE
Error when trying to install a new (version of a) plugin from file path

### ISSUE THREAD

**Issue by petrem** [tcorbettclark/encapsia-cli#76]
```
$ encapsia --host hostname plugins install path/to/plugin-foobar-1.0.0.tar.gz
Added to local store: path/to/plugin-foobar-1.0.0.tar.gz
Calling: api.run_view('pluginsmanager', 'installed_plugins_with_tags') (attempt 1/10)
Traceback (most recent call last):
  File "/home/kpp/.virtualenvs/encapsia/bin/encapsia", line 8, in <module>
    sys.exit(encapsia())
  File "/home/kpp/.virtualenvs/encapsia/lib/python3.8/site-packages/encapsia_cli/encapsia.py", line 141, in encapsia
    main(auto_envvar_prefix="ENCAPSIA")
  File "/home/kpp/.virtualenvs/encapsia/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kpp/.virtualenvs/encapsia/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kpp/.virtualenvs/encapsia/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kpp/.virtualenvs/encapsia/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kpp/.virtualenvs/encapsia/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kpp/.virtualenvs/encapsia/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kpp/.virtualenvs/encapsia/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/kpp/.virtualenvs/encapsia/lib/python3.8/site-packages/encapsia_cli/plugins.py", line 333, in install
    plan = _create_install_plan(
  File "/home/kpp/.virtualenvs/encapsia/lib/python3.8/site-packages/encapsia_cli/plugins.py", line 100, in _create_install_plan
    candidate = local_store.latest_version_matching_spec(spec)
  File "/home/kpp/.virtualenvs/encapsia/lib/python3.8/site-packages/encapsia_cli/plugininfo.py", line 281, in latest_version_matching_spec
    return PluginSpec.make_from_spec_or_string(spec).filter(self).latest()
  File "/home/kpp/.virtualenvs/encapsia/lib/python3.8/site-packages/encapsia_cli/plugininfo.py", line 361, in make_from_spec_or_string
    raise TypeError(f"Unknown spec type {type(spec_or_string)}")
TypeError: Unknown spec type <class 'encapsia_cli.plugininfo.PluginInfo'>

$ encapsia version
Encapsia CLI version: 0.5.0
Encapsia API version: 0.2.9

**Comment by petrem** [comment]
And a different flavour (when the path does not exist):

```
$ encapsia --host encval-v15-config plugins install plugin-foo-0.0.1.tar.gz
Traceback (most recent call last):
  File "/home/sforrer/.virtualenvs/encapsia/bin/encapsia", line 8, in <module>
    sys.exit(encapsia())
  File "/home/sforrer/.virtualenvs/encapsia/lib/python3.8/site-packages/encapsia_cli/encapsia.py", line 141, in encapsia
    main(auto_envvar_prefix="ENCAPSIA")
  File "/home/sforrer/.virtualenvs/encapsia/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sforrer/.virtualenvs/encapsia/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sforrer/.virtualenvs/encapsia/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sforrer/.virtualenvs/encapsia/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sforrer/.virtualenvs/encapsia/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sforrer/.virtualenvs/encapsia/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sforrer/.virtualenvs/encapsia/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/sforrer/.virtualenvs/encapsia/lib/python3.8/site-packages/encapsia_cli/plugins.py", line 315, in install
    to_install_candidates.append(PluginSpec.make_from_string(plugin))
  File "/home/sforrer/.virtualenvs/encapsia/lib/python3.8/site-packages/encapsia_cli/plugininfo.py", line 345, in make_from_string
    return cls(*cls._split_spec_string(spec_string), exact_match=exact_match)
  File "/home/sforrer/.virtualenvs/encapsia/lib/python3.8/site-packages/encapsia_cli/plugininfo.py", line 339, in _split_spec_string
    raise InvalidSpecError(f"Spec string {spec_string} is invalid.")
encapsia_cli.plugininfo.InvalidSpecError: Spec string plugin-abc-0.0.1.tar.gz is invalid.
```
